[all]
m1       ansible_connection=local ansible_user=root
lb01     ansible_host=10.0.0.11 ansible_user=root
lb02     ansible_host=10.0.0.12 ansible_user=root
web01    ansible_host=10.0.0.13 ansible_user=root
web02    ansible_host=10.0.0.14 ansible_user=root
db01     ansible_host=10.0.0.15 ansible_user=root
db02     ansible_host=10.0.0.16 ansible_user=root
monitor  ansible_host=10.0.0.17 ansible_user=root

[lb]
lb01
lb02

[web]
web01
web02

[db]
db01
db02

[monitoring]
monitor

[servers:children]
lb
web
db
monitoring
